version: "3.7"
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"

  server:
    build:
      dockerfile: Dockerfile
      context: "."
    command: npm run start:dev
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - ./client:/app

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"

  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3050:80"
